#!python

''' Display the legacy parameter ids for the parameters in a Bottle Exchange
file. 
'''

from __future__ import with_statement
import sys

import libcchdo as L
import libcchdo.model.datafile
from libcchdo.db.model import legacy
import libcchdo.formats.bottle.exchange as exbot


def get_legacy_parameter(session, parameter):
    if not parameter:
        return None
    name = parameter.name
    if name != '_DATETIME':
        return legacy.find_parameter(session, name)
    return None


def main(argv):
    if len(argv) < 2:
        print 'Usage:', argv[0], '<exbot file>'
        return 1
    
    with open(argv[1], 'r') as in_file:
        file = L.model.datafile.DataFile()
        exbot.read(file, in_file)
    
        # Get STD parameters from bottle file
        parameters = file.get_property_for_columns(lambda x: x.parameter)
    
        print 'Parameters for the data set are: ', parameters
        print 'Getting legacy parameters'
    
        legacy_session = legacy.session()
        legacy_parameters = filter(
            None,
            [get_legacy_parameter(legacy_session, x) for x in parameters])
        legacy_session.close()
    
        print map(lambda x: int(x.id) if x.id else None, legacy_parameters)
        print map(lambda x: x.name, legacy_parameters)


if __name__ == '__main__':
    sys.exit(main(sys.argv))
